/*
 * Loads the built CommonJS bundle inside a sandbox with stand-ins for
 * React and React Native, so every test below runs the shipped code
 * rather than the source, and none of them touches the network.
 *
 * The payloads under fixtures/ were captured from a real brand. They are
 * regenerated by refetching, never edited by hand: a fixture somebody
 * tidied up stops being evidence of anything. The one exception is
 * removal. This repository is public, and a captured discovery document
 * carries entries for things that are not released, so anything this
 * package has no address for is dropped on capture. Nothing is ever
 * rewritten, and a test that needs an entry the package cannot reach
 * builds it in the test, where it is obviously a stand-in.
 *
 * Build first: npm run build (the package test script does this).
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";

const here = dirname(fileURLToPath(import.meta.url));
export const packageRoot = join(here, "..");

const BUNDLE = readFileSync(join(packageRoot, "dist", "index.cjs"), "utf8");

export function fixture(name) {
  return JSON.parse(readFileSync(join(packageRoot, "fixtures", name), "utf8"));
}

export function fixtureText(name) {
  return readFileSync(join(packageRoot, "fixtures", name), "utf8");
}

/** A response in the shape the package reads. */
export function jsonResponse(body, headers = {}, status = 200) {
  const lower = {};
  for (const key of Object.keys(headers)) lower[key.toLowerCase()] = headers[key];
  return {
    ok: status >= 200 && status < 300,
    status,
    headers: {
      get: (name) => (name.toLowerCase() in lower ? lower[name.toLowerCase()] : null),
      /* The platform Headers can be walked, and the version reader walks
       * it to find which prefix the three values arrived under. */
      forEach: (visit) => {
        for (const key of Object.keys(lower)) visit(lower[key], key);
      },
    },
    text: async () => (typeof body === "string" ? body : JSON.stringify(body)),
  };
}

/**
 * A fetch that answers from a table of url substrings. Records every
 * address it was asked for, which is how the address tests read.
 */
export function routedFetch(routes) {
  const calls = [];
  const impl = async (url) => {
    calls.push(url);
    for (const [match, answer] of routes) {
      if (url.includes(match)) {
        return typeof answer === "function" ? answer(url) : answer;
      }
    }
    return jsonResponse({ error: "Not found" }, {}, 404);
  };
  impl.calls = calls;
  return impl;
}

/** An XMLHttpRequest that replays a recorded stream in chunks. */
export function replayingXhr(chunks) {
  const opened = [];
  class Replay {
    constructor() {
      this.readyState = 0;
      this.status = 0;
      this.responseText = "";
      this.onreadystatechange = null;
      this.onerror = null;
      this.onabort = null;
      this._timers = [];
    }
    open(method, url) {
      opened.push(url);
      this.readyState = 1;
    }
    setRequestHeader() {}
    send() {
      this.status = 200;
      let delay = 0;
      for (const chunk of chunks) {
        delay += 1;
        this._timers.push(
          setTimeout(() => {
            this.responseText += chunk;
            this.readyState = 3;
            if (this.onreadystatechange) this.onreadystatechange();
          }, delay),
        );
      }
    }
    abort() {
      for (const timer of this._timers) clearTimeout(timer);
      this._timers = [];
      if (this.onabort) this.onabort();
    }
  }
  Replay.opened = opened;
  return Replay;
}

/** The React Native surface this package touches, and nothing else. */
function reactNativeStub(overrides = {}) {
  const bezier = (a, b, c, d) => {
    const fn = (value) => value;
    fn.points = [a, b, c, d];
    return fn;
  };
  return {
    AppState: {
      currentState: "active",
      addEventListener: () => ({ remove() {} }),
      ...(overrides.AppState || {}),
    },
    Appearance: {
      getColorScheme: () => "dark",
      addChangeListener: () => ({ remove() {} }),
      ...(overrides.Appearance || {}),
    },
    Image: Object.assign(function Image() {}, {
      prefetch: async () => true,
      ...(overrides.Image || {}),
    }),
    Platform: { OS: "ios", ...(overrides.Platform || {}) },
    PixelRatio: { get: () => 3, ...(overrides.PixelRatio || {}) },
    Easing: { linear: (value) => value, bezier },
    StyleSheet: { create: (styles) => styles },
    StatusBar: { currentHeight: 24 },
  };
}

/*
 * React, reduced to the parts this package uses, with hook state that
 * survives a re-render.
 *
 * The earlier stub answered useMemo by calling the factory and throwing
 * the dependency array away, and useState by handing back the initial
 * value and a setter that did nothing. Under that stub every call of a
 * component is a first render, so the one thing a memo can get wrong --
 * holding last render's value after its dependencies moved -- was not
 * reachable by any test. A hook that never recomputed and a hook that
 * always recomputed produced identical output, and the suite was green
 * either way. That is how a stale useBrandAsset shipped: the address kept
 * the appearance it was first built with, and 102 passing tests had no
 * way to notice.
 *
 * So the stub keeps a slot per hook call site per mounted component,
 * compares dependency arrays the way React does, runs effects and their
 * cleanups, and re-renders when a setter is called.
 *
 * Calling a component function directly, without mount(), still works and
 * is still a first render: slots are per-instance, and there is no
 * instance. Use it to assert what a component returns. Use mount() for
 * anything about how it answers a CHANGE.
 */
function reactStub(holder) {
  /* The instance being rendered right now, or null outside a render. */
  let frame = null;

  function sameDeps(before, now) {
    /* No array at all means "recompute every render", as in React. */
    if (!Array.isArray(before) || !Array.isArray(now)) return false;
    if (before.length !== now.length) return false;
    for (let i = 0; i < before.length; i += 1) {
      /* Object.is, which is what React compares with. */
      if (!Object.is(before[i], now[i])) return false;
    }
    return true;
  }

  function slot() {
    if (!frame) return null;
    const index = frame.index;
    frame.index += 1;
    if (!frame.instance.slots[index]) frame.instance.slots[index] = {};
    return frame.instance.slots[index];
  }

  const stub = {
    createContext: (value) => ({
      Provider: "DesignlessProvider",
      Consumer: "DesignlessConsumer",
      _value: value,
    }),
    createElement: (type, props, ...children) => ({ type, props, children }),
    /* Whatever the test put in context, which is null until it does. The
     * package has its own guard for that and it should be the one to
     * fire, not this stub. */
    useContext: () => holder.value,
    useEffect: (fn, deps) => {
      const cell = slot();
      if (!cell) return;
      /* Queued, not run here: an effect that fires mid-render could set
       * state into a render that has not finished. */
      frame.pending.push({ cell, fn, deps });
    },
    useMemo: (factory, deps) => {
      const cell = slot();
      if (!cell) return factory();
      if (cell.filled && sameDeps(cell.deps, deps)) return cell.value;
      cell.filled = true;
      cell.deps = deps;
      cell.value = factory();
      return cell.value;
    },
    useRef: (initial) => {
      const cell = slot();
      if (!cell) return { current: initial };
      if (!cell.filled) {
        cell.filled = true;
        cell.value = { current: initial };
      }
      return cell.value;
    },
    useState: (initial) => {
      const cell = slot();
      if (!cell) return [initial, () => {}];
      if (!cell.filled) {
        cell.filled = true;
        cell.value = typeof initial === "function" ? initial() : initial;
      }
      const instance = frame.instance;
      const set = (next) => {
        const value = typeof next === "function" ? next(cell.value) : next;
        if (Object.is(value, cell.value)) return;
        cell.value = value;
        if (!instance.alive) return;
        instance.render();
      };
      return [cell.value, set];
    },
  };

  /**
   * Render a component and keep it mounted.
   *
   * `.output` is what the last render returned. `.renders` counts them,
   * which is how a test tells "recomputed" from "returned the same value
   * twice". `.unmount()` runs the effect cleanups.
   */
  function mount(component, props = {}) {
    const instance = {
      slots: [],
      alive: true,
      renders: 0,
      output: null,
      props,
    };

    instance.render = () => {
      const previous = frame;
      frame = { instance, index: 0, pending: [] };
      let pending;
      try {
        instance.output = component(instance.props);
        instance.renders += 1;
        pending = frame.pending;
      } finally {
        frame = previous;
      }
      for (const effect of pending) {
        if (effect.cell.filled && sameDeps(effect.cell.deps, effect.deps)) continue;
        if (typeof effect.cell.cleanup === "function") effect.cell.cleanup();
        effect.cell.filled = true;
        effect.cell.deps = effect.deps;
        effect.cell.cleanup = effect.fn();
      }
      return instance.output;
    };

    instance.rerender = (nextProps) => {
      if (nextProps !== undefined) instance.props = nextProps;
      return instance.render();
    };

    instance.unmount = () => {
      instance.alive = false;
      for (const cell of instance.slots) {
        if (cell && typeof cell.cleanup === "function") cell.cleanup();
      }
    };

    instance.render();
    return instance;
  }

  return { stub, mount };
}

/*
 * Every brand any test has made, so none of them can outlive it.
 *
 * A brand holds timers: a reconnect, a schedule, a font retry. An
 * assertion that throws skips the destroy() written after it, and the
 * runner then waits on timers that reschedule themselves, which is a
 * failing test that never finishes rather than one that reports. So
 * createBrand is wrapped on the way out and every test file clears the
 * list afterwards, whichever way the test ended.
 */
const madeBrands = [];

export function cleanupBrands() {
  while (madeBrands.length) {
    const brand = madeBrands.pop();
    try {
      brand.destroy();
    } catch {
      /* Already gone, which is the state being asked for. */
    }
  }
}

/**
 * Load the bundle. Returns its exports plus the warnings it emitted, so a
 * test can assert on the development guidance as well as the behaviour.
 */
export function loadPackage(options = {}) {
  const warnings = [];
  const inContext = { value: null };
  const react = reactStub(inContext);
  const modules = {
    react: react.stub,
    "react-native": reactNativeStub(options.reactNative),
  };
  const sandbox = {
    module: { exports: {} },
    require: (id) => {
      if (id in modules) return modules[id];
      throw new Error("unexpected import: " + id);
    },
    console: {
      warn: (message) => warnings.push(String(message)),
      error: () => {},
      log: () => {},
    },
    setTimeout,
    clearTimeout,
    setInterval,
    clearInterval,
    __DEV__: options.dev !== false,
    fetch: options.fetch,
    XMLHttpRequest: options.XMLHttpRequest,
  };
  sandbox.exports = sandbox.module.exports;
  const context = vm.createContext(sandbox);
  vm.runInContext(BUNDLE, context, { filename: "designless-react-native.cjs" });
  /* Copied rather than patched: the bundle defines its exports as getters. */
  const exported = sandbox.module.exports;
  const api = Object.assign({}, exported, {
    createBrand: (brandOptions) => {
      const brand = exported.createBrand(brandOptions);
      madeBrands.push(brand);
      return brand;
    },
  });
  return {
    api,
    warnings,
    native: modules["react-native"],
    /** Put a brand where the provider would have put it. */
    provide: (brand) => {
      inContext.value = brand;
    },
    /**
     * Mount a component and keep it mounted, so a test can assert on how
     * it answers a change rather than only on a first render. Required
     * for anything about memo invalidation.
     */
    mount: react.mount,
  };
}

/** A snapshot built from a captured payload. */
export function snapshotFrom(tokensFixture, fontsPresent = [], overrides = {}) {
  return {
    $schema: "designless-native-snapshot/v1",
    publicId: "_designless",
    fetchedAt: new Date().toISOString(),
    appearance: "dark",
    version: { hash: "snapshot-hash", semver: "1.0.1", version: 2 },
    tokens: fixture(tokensFixture),
    fonts: fixture("fonts.json"),
    fontsPresent,
    ...overrides,
  };
}

/** Let queued promises and zero-delay timers run. */
export function settle(times = 4) {
  let chain = Promise.resolve();
  for (let i = 0; i < times; i += 1) {
    chain = chain.then(() => new Promise((resolve) => setTimeout(resolve, 2)));
  }
  return chain;
}
